#!/bin/sh
#
# @name Custom DShot
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Weisheng Liang <wshg.liang@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

### Controller Gain from 4011_dji_f450
param set-default MC_ROLL_P 7
param set-default MC_ROLLRATE_P 0.15
param set-default MC_ROLLRATE_I 0.05
param set-default MC_ROLLRATE_D 0.003
param set-default MC_PITCH_P 7
param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.003
param set-default MC_YAW_P 2.8
param set-default MC_YAWRATE_P 0.3
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0

### Thrust Model
param set-default THR_MDL_FAC 0.75

### ESCs
# DShot
param set-default SYS_USE_IO 0 # FMU
param set-default DSHOT_CONFIG 600

### Auto-disarm disable
# param set-default COM_DISARM_LAND -1
# param set-default COM_DISARM_PRFLT -1

### Data link loss failsafe
param set-default NAV_DLL_ACT 0 # Disabled

### RTPS
param set-default MAV_1_CONFIG 0 # MAVLink (instance 1) Disabled
param set-default RTPS_CONFIG 102 # FastRTPS TELEM 2
param set-default SER_TEL2_BAUD 1500000 # Baudrate

### RC Setting
# RC Map
param set-default RC_MAP_OFFB_SW 6
param set-default RC_MAP_KILL_SW 8
param set-default RC_MAP_FLTMODE 5

# Flight Modes
param set-default COM_FLTMODE1 8 # Stabilized
param set-default COM_FLTMODE4 2 # Position
param set-default COM_FLTMODE6 11 # Land

### Battery
param set-default BAT1_N_CELLS 4
param set-default BAT1_V_CHARGED 4.2
param set-default BAT1_V_EMPTY 3.7
param set-default BAT1_V_DIV 18.182
param set-default BAT1_A_PER_V 36.364

# The following parameters are compatible with QGC
param set-default BAT_N_CELLS 4
param set-default BAT_V_CHARGED 4.2
param set-default BAT_V_EMPTY 3.7
param set-default BAT_V_DIV 18.182
param set-default BAT_A_PER_V 36.364

### EKF2
# param set-default SENS_EN_PX4FLOW 1
# param set-default SENS_EN_MB12XX 1
# param set-default SENS_TFMINI_CFG 104 # TELEM/SERIAL 4
# param set-default EKF2_RNG_AID 1
param set-default EKF2_HGT_MODE 3 # Vision
param set-default EKF2_AID_MASK 280 # EV_POS + EV_VEL + EV_YAW

# Multi-EKF
param set-default EKF2_MULTI_IMU 2 # Requires SENS_IMU_MODE 0
param set-default SENS_IMU_MODE 0 # Publish all IMUs
param set-default EKF2_MULTI_MAG 2 # Requires SENS_MAG_MODE 0
param set-default SENS_MAG_MODE 0 # Publish all magnetometers

### Failure Detector
param set-default FD_FAIL_R 65
param set-default FD_FAIL_P 65

### PX4 Logger
param set-default SDLOG_MODE 2 # from boot until shutdown
